apiVersion: v1
kind: Service
metadata:
  labels:
    app: sonar-postgres
  name: sonar-postgres
spec:
  ports:
    - port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    app: sonar-postgres
  sessionAffinity: None
  type: ClusterIP
