apiVersion: v1
kind: Service
metadata:
  labels:
    app: sonar
  name: sonar
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 9000
  selector:
    app: sonar
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata: 
  labels:
    app: sonar
  name: sonar
spec: 
  virtualhost:
    fqdn: sonar.local
  routes: 
    - conditions:
      - prefix: /
      services:
        - name: sonar
          port: 80
