apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonar
spec:
  selector:
      matchLabels:
        app: sonar
  replicas: 1
  template:
    metadata:
      name: sonar
      labels:
        app: sonar
    spec:
      containers:
        - image: sonarqube:latest
          name: sonar
          env:
            - name: SONARQUBE_JDBC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-pwd
                  key: password
            - name: SONARQUBE_JDBC_URL
              value: jdbc:postgresql://sonar-postgres:5432/sonar
            - name: SONARQUBE_JDBC_USERNAME
              value: sonar
          ports:
            - containerPort: 9000
              name: sonar
      initContainers:
        - name: sysctl
          image: busybox:1.28
          securityContext:
            privileged: true
          command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144; sysctl -w fs.file-max=65536; ulimit -n 65536; ulimit -u 4096']
